export const assistantExamples = [
  "Who lives at Loch Lomand?",
  "What is the tenant email for Loch Lomand?",
  "What are the tenant notes for Loch Lomand?",
  "How long has each tenant been in their house?",
  "What is the gate code at Loch Lomand?",
  "Which leases expire within 90 days?",
  "Which move-ins are upcoming?",
  "Which tenants have birthdays this month?",
  "Summarize the rental application for Verona.",
  "What maintenance has been completed at Estates?",
  "Which houses need new AC units?",
  "Show financial files for St. Paul.",
  "What templates are available?",
  "Find the Move-In Checklist.",
  "Generate a Move-In Checklist for Loch Lomand.",
  "Draft a tenant text for Loch Lomand.",
  "Generate a rent increase notice for Loch Lomand.",
];
